# Time in seconds
# Current in amps
# position, velocity, and acceleration in device units
left_drive_actuator:
  actuator_name: walrus/left_drive_actuator
  serial_number: '662080000026'

right_drive_actuator:
  actuator_name: walrus/right_drive_actuator
  serial_number: '662080000026'
