language:
  - cpp
compiler:
  - gcc

branches:
  only:
    - master

install:
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu precise main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install python-catkin-pkg python-rosdep python-catkin-tools ros-hydro-catkin ros-hydro-ros-base -qq
  - sudo apt-get install arduino-core -qq
  - sudo rosdep init
  - rosdep update
  - mkdir -p /tmp/ws/src
  - ln -s `pwd` /tmp/ws/src/package
  - cd /tmp/ws/src
  - git clone https://github.com/ros-drivers/rosserial.git
  - cd /tmp/ws
  - rosdep install --from-paths src --ignore-src --rosdistro hydro -y

script:
  - source /opt/ros/hydro/setup.bash
  - catkin build
  - catkin config --install
  - catkin clean -b
  - catkin build
  - source install/setup.bash
