pub_rate: 1.0
analyzers:
  computers:
    type: diagnostic_aggregator/GenericAnalyzer
    path: Primary Computer
    startswith: 'walrus/primary_computer_monitor: '
    remove_prefix: 'walrus primary_computer_monitor: '
  robot_hw:
    type: diagnostic_aggregator/GenericAnalyzer
    path: Robot Hardware
    startswith: 'walrus/walrus_base_hw: '
    remove_prefix: 'walrus walrus_base_hw: '
