pub_rate: 1.0
analyzers:
  computers:
    type: GenericAnalyzer
    path: Primary Computer
    startswith: 'walrus/primary_computer_monitor: '
    remove_prefix: 'walrus primary_computer_monitor: '
#    find_and_remove_prefix: 'primary_computer_monitor:'
