pub_rate: 1.0
analyzers:
  chassis:
    type: diagnostic_aggregator/GenericAnalyzer
    path: Chassis
    contains: 'Water'
    expected: [
        'base: Top Plate Temperature',
        'base: Internal Temperature',
        'base: Internal Humidity',
        'base: Internal Pressure']
    remove_prefix: 'base: '
  computers:
    type: diagnostic_aggregator/AnalyzerGroup
    path: Computers
    analyzers:
      primary_computer:
        type: diagnostic_aggregator/AnalyzerGroup
        path: Primary Computer
        analyzers:
          sensors:
            type: diagnostic_aggregator/GenericAnalyzer
            path: Sensors
            find_and_remove_prefix: 'primary_computer_sensors_monitor: '
          resources:
            type: diagnostic_aggregator/GenericAnalyzer
            path: Resources
            find_and_remove_prefix: 'primary_computer_resource_monitor: '
  environment:
    type: diagnostic_aggregator/GenericAnalyzer
    path: Environment
    contains: [
        'boom: CO Concentration',
        'boom: CNG Concentration',
        'boom: LPG Concentration',
        'boom: H Concentration']
    remove_prefix: 'boom: '              
  embedded:
    type: diagnostic_aggregator/GenericAnalyzer
    path: Embedded Boards
    expected: [
        'base: Main Control Board']
    contains: [
        'boom: Boom Control Board']
    remove_prefix: 'base: '
  imu:
    type: diagnostic_aggregator/GenericAnalyzer
    path: IMU
    find_and_remove_prefix: 'orientus_node: '
  drive:
    type: diagnostic_aggregator/AnalyzerGroup
    path: Drive
    analyzers:
        left_drive:
            type: diagnostic_aggregator/GenericAnalyzer
            path: Left Drive
            expected: [
                'base: Left Drive Motor Temperature', 
                'base_epos: left_drive_actuator: Motor',
                'base_epos: left_drive_actuator: Motor Output']
            remove_prefix: 'base: '
        right_drive:
            type: diagnostic_aggregator/GenericAnalyzer
            path: Right Drive
            expected: [
                'base: Right Drive Motor Temperature',
                'base_epos: right_drive_actuator: Motor',
                'base_epos: right_drive_actuator: Motor Output']
            remove_prefix: 'base: '
  pods:
    type: diagnostic_aggregator/GenericAnalyzer
    path: Pods
    expected: [
        'base: Front Left Pod',
        'base: Front Right Pod',
        'base: Back Right Pod',
        'base: Back Left Pod']
    remove_prefix: 'base: '
  power:
    type: diagnostic_aggregator/GenericAnalyzer
    path: Power
    expected: [
        'base: Power Systems',
        'base: Battery 1',
        'base: Battery 2',
        'base: Battery 3',
        'base: Battery 4']
    remove_prefix: 'base: '
  boom:
    type: diagnostic_aggregator/GenericAnalyzer
    path: Boom
    contains: [
        'boom: Pan Control',
        'boom: Tilt Control',
        'boom: Deploy Control']
    remove_prefix: 'boom: '
  networking:
    type: diagnostic_aggregator/AnalyzerGroup
    path: Networking
    analyzers:
      robot_bullet:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Robot Bullet
        find_and_remove_prefix: 'robot_bullet_monitor: '
      remote_bullet:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Remote Bullet
        find_and_remove_prefix: 'remote_bullet_monitor: '
