pub_rate: 1.0
analyzers:
  chassis:
    type: diagnostic_aggregator/GenericAnalyzer
    path: Chassis
    contains: 'Water'
    expected: [
        'base_mainboard: Top Plate Temperature',
        'base_mainboard: Internal Temperature',
        'base_mainboard: Internal Humidity',
        'base_mainboard: Internal Pressure']
    remove_prefix: 'base_mainboard: '
  computers:
    type: diagnostic_aggregator/AnalyzerGroup
    path: Computers
    analyzers:
      primary_computer:
        type: diagnostic_aggregator/AnalyzerGroup
        path: Primary Computer
        analyzers:
          sensors:
            type: diagnostic_aggregator/GenericAnalyzer
            path: Sensors
            find_and_remove_prefix: 'primary_computer_sensors_monitor: '
          resources:
            type: diagnostic_aggregator/GenericAnalyzer
            path: Resources
            find_and_remove_prefix: 'primary_computer_resource_monitor: '
  environment:
    type: diagnostic_aggregator/GenericAnalyzer
    path: Environment
    contains: [
        'boom: Temperature',
        'boom: Humidity',
        'boom: CO Concentration',
        'boom: CNG Concentration',
        'boom: LPG Concentration',
        'boom: Hydrogen Concentration']
    remove_prefix: 'boom: '              
  embedded:
    type: diagnostic_aggregator/GenericAnalyzer
    path: Embedded Boards
    expected: [
        'base_mainboard: Main Control Board']
    contains: [
        'boom: Boom Control Board']
    remove_prefix: 'base_mainboard: '
  imu:
    type: diagnostic_aggregator/GenericAnalyzer
    path: IMU
    find_and_remove_prefix: 'orientus_node: '
  drive:
    type: diagnostic_aggregator/AnalyzerGroup
    path: Drive
    analyzers:
        left_drive:
            type: diagnostic_aggregator/GenericAnalyzer
            path: Left Drive
            expected: [
                'base_mainboard: Left Drive Motor Temperature', 
                'base_epos: left_drive_actuator: Motor',
                'base_epos: left_drive_actuator: Motor Output']
            remove_prefix: 'base_epos: '
        right_drive:
            type: diagnostic_aggregator/GenericAnalyzer
            path: Right Drive
            expected: [
                'base_mainboard: Right Drive Motor Temperature',
                'base_epos: right_drive_actuator: Motor',
                'base_epos: right_drive_actuator: Motor Output']
            remove_prefix: 'base_epos: '
  pods:
    type: diagnostic_aggregator/GenericAnalyzer
    path: Pods
    expected: [
        'base_mainboard: Front Left Pod Temperature',
        'base_mainboard: Front Right Pod Temperature',
        'base_mainboard: Back Right Pod Temperature',
        'base_mainboard: Back Left Pod Temperature',
        'base: Front Pod Controller',
        'base: Back Pod Controller',
        'base: Front Left Pod Control',
        'base: Front Right Pod Control',
        'base: Back Right Pod Control',
        'base: Back Left Pod Control']
    remove_prefix: 'base: '
  power:
    type: diagnostic_aggregator/GenericAnalyzer
    path: Power
    expected: [
        'base_mainboard: Power Systems',
        'base_mainboard: Battery 1',
        'base_mainboard: Battery 2',
        'base_mainboard: Battery 3',
        'base_mainboard: Battery 4']
    remove_prefix: 'base_mainboard: '
  boom:
    type: diagnostic_aggregator/GenericAnalyzer
    path: Boom
    contains: [
        'boom: Pan Control',
        'boom: Tilt Control',
        'boom: Deploy Control']
    remove_prefix: 'boom: '
  networking:
    type: diagnostic_aggregator/AnalyzerGroup
    path: Networking
    analyzers:
      robot_bullet:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Robot Bullet
        find_and_remove_prefix: 'robot_bullet_monitor: '
      remote_bullet:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Remote Bullet
        find_and_remove_prefix: 'remote_bullet_monitor: '
