pub_rate: 1.0
analyzers:
  computers:
    type: diagnostic_aggregator/GenericAnalyzer
    path: Primary Computer
    startswith: 'walrus/primary_computer_monitor: '
    remove_prefix: 'walrus primary_computer_monitor: '
  imu:
    type: diagnostic_aggregator/GenericAnalyzer
    path: IMU
    startswith: 'walrus/orientus_node: '
    remove_prefix: 'walrus orientus_node: '
  robot_hw:
    type: diagnostic_aggregator/GenericAnalyzer
    path: Robot Hardware
    startswith: 'walrus/walrus_base_hw: '
    remove_prefix: 'walrus walrus_base_hw: '
  networking:
    type: diagnostic_aggregator/AnalyzerGroup
    path: Networking
    analyzers:
      robot_bullet:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Robot Bullet
        startswith: 'walrus/robot_bullet_monitor: '
        remove_prefix: 'walrus robot_bullet_monitor: '
      remote_bullet:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Remote Bullet
        startswith: 'walrus/remote_bullet_monitor: '
        remove_prefix: 'walrus remote_bullet_monitor: '
