pub_rate: 1.0
analyzers:
  computers:
    type: diagnostic_aggregator/AnalyzerGroup
    path: Computers
    analyzers:
      primary_computer:
        type: diagnostic_aggregator/AnalyzerGroup
        path: Primary Computer
        analyzers:
          sensors:
            type: diagnostic_aggregator/GenericAnalyzer
            path: Sensors
            find_and_remove_prefix: 'walrus/primary_computer_sensors_monitor: '
          resources:
            type: diagnostic_aggregator/GenericAnalyzer
            path: Resources
            find_and_remove_prefix: 'walrus/primary_computer_resource_monitor: '
  imu:
    type: diagnostic_aggregator/GenericAnalyzer
    path: IMU
    find_and_remove_prefix: 'walrus/orientus_node: '
  robot_hw:
    type: diagnostic_aggregator/GenericAnalyzer
    path: Robot Hardware
    find_and_remove_prefix: 'walrus/walrus_base_hw: '
  networking:
    type: diagnostic_aggregator/AnalyzerGroup
    path: Networking
    analyzers:
      robot_bullet:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Robot Bullet
        find_and_remove_prefix: 'walrus/robot_bullet_monitor: '
      remote_bullet:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Remote Bullet
        find_and_remove_prefix: 'walrus/remote_bullet_monitor: '
