frontleft_pod_position_index: 0
frontright_pod_position_index: 1
backright_pod_position_index: 3
backleft_pod_position_index: 2
frontleft_pod_channel: 2
frontright_pod_channel: 1
backright_pod_channel: 1
backleft_pod_channel: 2
frontleft_pod_neutral_position: 0.900
frontright_pod_neutral_position: 1.981
backright_pod_neutral_position: -2.619
backleft_pod_neutral_position: 2.871
frontleft_pod_encoder_reverse: true
frontright_pod_encoder_reverse: false
backright_pod_encoder_reverse: false
backleft_pod_encoder_reverse: true
frontleft_pod_motor_reverse: false
frontright_pod_motor_reverse: false
backright_pod_motor_reverse: true
backleft_pod_motor_reverse: false
pod_output_torque_per_amp: 29.184
pod_motor_current_high_above: -1.0
pod_motor_limit: 0.4