boom:
  deploy_controller:
    type: position_effort_controller/PositionEffortController
    joint: walrus/boom/deploy_joint
    pid: {p : 5.0, i : 0.0, d : 0.0}
  pan_controller:
    type: position_effort_controller/PositionEffortController
    joint: walrus/boom/pan_joint
    pid: {p : 5.0, i : 0.0, d : 0.0}
  tilt_controller:
    type: position_effort_controller/PositionEffortController
    joint: walrus/boom/tilt_joint
    pid: {p : 5.0, i : 0.0, d : 0.0}
