# Publish joint states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Pod Controller
front_left_pod_joint_controller:
  type: position_controllers/JointPositionController
  joint: walrus/front_left_pod_joint
back_left_pod_joint_controller:
  type: position_controllers/JointPositionController
  joint: walrus/back_left_pod_joint
front_right_pod_joint_controller:
  type: position_controllers/JointPositionController
  joint: walrus/front_right_pod_joint
back_right_pod_joint_controller:
  type: position_controllers/JointPositionController
  joint: walrus/back_right_pod_joint

# Drive Controllers
left_drive_controller:
  type: velocity_controllers/JointVelocityController
  joint: walrus/left_drive_joint
right_drive_controller:
  type: velocity_controllers/JointVelocityController
  joint: walrus/right_drive_joint

#Boom
boom_deploy_controller:
  type: position_controllers/JointPositionController
  joint: walrus/boom/deploy_joint
boom_pan_controller:
  type: position_controllers/JointPositionController
  joint: walrus/boom/pan_joint
boom_tilt_controller:
  type: position_controllers/JointPositionController
  joint: walrus/boom/tilt_joint
